Fix 32 bits build
Dividing a u64 in 32bits architecture would produce the error :
	vd55g1.c:(.text+0x1e38): undefined reference to `__udivdi3'
Change mipi_freq variable type to u32 instead of using div helpers as it
is enough to store its value anyway.

Signed-off-by: Benjamin Mugnier <benjamin.mugnier@foss.st.com>